Workers
codex-team/domain-checker pull request #10
Opened 2018-11-15 15:47 UTC by kabachook

2018-11-15 16:41 UTC, neSpecc requested changes

2018-11-15 16:41 UTC, neSpecc commented on backend/src/workers/responder.js
> +const CLEAN_TIMEOUT = 5 * 60 * 1000;
надо описать константу

2018-11-15 16:41 UTC, neSpecc commented on backend/src/workers/responder.js
> +   *    id,
объекты не так документируются

2018-11-17 13:01 UTC, neSpecc approved these changes

2018-11-17 13:30 UTC, khaydarov approved these changes

2018-11-17 14:09 UTC, merged