Design update
codex-team/domain-checker pull request #14
Opened 2018-11-20 18:31 UTC by nikmel2803

2018-11-20 18:45 UTC, neSpecc requested changes
- подключить PostCSS и переписать стили с его использованием
- переписать селекторы на бэм 
- цвета вынести в переменные

2018-11-20 18:45 UTC, neSpecc commented on frontend/src/css/main.css
> +    max-width: 500px;
не стоит ограничивать все тело документа.

2018-11-20 23:11 UTC, neSpecc approved these changes

2018-11-21 13:14 UTC, khaydarov requested changes

2018-11-21 13:14 UTC, khaydarov commented on frontend/src/js/index.js
> +      child.classList.add('results__result');
Давай названия классов вынесем в константы, как у нас в других проектах. Так можно в одном месте поменять и во всех селекциях будет использоваться

2018-11-21 13:16 UTC, neSpecc commented on frontend/src/js/index.js
> +      child.classList.add('results__result');
лучше тогда все в одну константу: 

```js
const CSS = {
   wrapper: '',
   results: '',
   resultsItem: '' 
}
```

2018-11-21 14:44 UTC, khaydarov approved these changes

2018-11-21 15:05 UTC, neSpecc approved these changes

2018-11-21 15:06 UTC, merged