Frontend update
codex-team/domain-checker pull request #17
Opened 2018-11-21 19:41 UTC by nikmel2803

2018-11-22 10:24 UTC, neSpecc approved these changes

2018-11-22 10:24 UTC, neSpecc commented on frontend/src/js/utils/validateDomainName.js
> +    tooShort: 'Domain name is too short',
не нужно показывать эти ошибки пользователю, просто запрос не будет отправляться

2018-11-22 10:24 UTC, neSpecc requested changes

2018-11-22 10:24 UTC, neSpecc commented on frontend/src/js/utils/validateDomainName.js
> +    tooShort: 'Domain name is too short',
.

2018-11-22 13:23 UTC, neSpecc requested changes

2018-11-22 13:23 UTC, neSpecc commented on frontend/src/js/index.js
>      const newAvailableDomainHandler = (availableTLD) => {
вынеси эту функцию из обработчика inputHandler. Зачем ее при каждом нажатии заново создавать?

2018-11-24 17:18 UTC, neSpecc approved these changes

2018-11-24 17:58 UTC, khaydarov approved these changes

2018-11-24 19:42 UTC, merged