Dns worker
codex-team/domain-checker pull request #28
Opened 2018-12-03 12:22 UTC by nikmel2803

Реализация воркера, который по DNS проверяет доступен ли домен

2018-12-03 15:40 UTC, kabachook commented
Closes #23

2018-12-04 12:43 UTC, khaydarov requested changes

2018-12-04 12:43 UTC, khaydarov commented on backend/src/workers/dns/checkDomain.js
> +const getDNSStatus = async (name, tld, recordType) => {
функция должна вернуть promise<number>, в случае когда сработает catch, у тебя выведется лог и функция, которая вызывает эту функцию не получит в итоге число. У тебя где-то обрабатывается это?

2018-12-04 12:43 UTC, khaydarov commented on backend/src/workers/dns/checkDomain.js
> +    console.log('HTTPS request error' + e);
может вернешь 0 или null?

2018-12-04 12:43 UTC, khaydarov commented on backend/src/workers/dns/checkDomain.js
> +    if (dnsStatus === 0) {
а тут у тебя закончится цепочка вызовов

2018-12-04 12:43 UTC, khaydarov commented on backend/src/workers/dns/index.js
> +const { checkDomain } = require('./checkDomain');
давай либо с пробелами либо без, что-то одно

2018-12-04 14:13 UTC, neSpecc requested changes

2018-12-04 14:13 UTC, neSpecc commented on backend/src/workers/dns/checkDomain.js
> +    if (dnsStatus === 0) {
нигде не описано магическое число 0

2018-12-04 14:13 UTC, neSpecc commented on backend/src/workers/dns/checkDomain.js
> + * @returns {boolean} true if available else false.
`{Promise<boolean>}`

2018-12-04 15:32 UTC, khaydarov approved these changes

2018-12-04 15:58 UTC, neSpecc approved these changes

2018-12-04 16:00 UTC, merged