Task queue
codex-team/domain-checker pull request #3
Opened 2018-11-07 11:59 UTC by kabachook

- Redis' list as queue (`lpush` and `brpop`)

2018-11-07 12:22 UTC, neSpecc requested changes

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.js
> +class JsonParser extends Parser {
лучше вынести в отдельные файлы. И в начале файла нужно подробно описать, что это, зачем он нужен и как работает

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.js
> +    this.prefix = prefix;
отделяй смысловые части пустыми строками

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.js
> +   * @param {string} [prefix='queue:'] Prefix.
префикс чего? для чего нужен

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.js
> +    this._fullName = prefix + queueName;
свойства класса надо описать в комментах

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.test.js
> +  beforeAll(() => {
все методы и смысловые части надо задокументировать

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.test.js
> +const QUEUE_TIMEOUT = 30;
все константы надо задокументировать

2018-11-07 12:22 UTC, neSpecc commented on task-queue/lib/queue.js
> +   * Prepare message
надо пояснить, какие действия входят в prepare

2018-11-07 13:27 UTC, khaydarov requested changes

2018-11-07 13:27 UTC, khaydarov commented on task-queue/lib/queue.js
> +  parse() {
функция не принимает ничего, а в JSDoc ты указал msg

2018-11-07 13:27 UTC, khaydarov commented on task-queue/lib/queue.js
> +   * @throws {Error}
@throws {ParserError}

2018-11-07 13:27 UTC, khaydarov commented on task-queue/lib/queue.js
> +    } catch (e) {
e - нигде не используется
и добавь throws

2018-11-07 13:27 UTC, khaydarov commented on task-queue/lib/queue.js
> + * Queue base class.
Опиши подробнее класс. Зачем он нужен, как использовать и какие задачи решает

2018-11-07 13:27 UTC, khaydarov commented on task-queue/lib/queue.js
> +   *
лишнее

2018-11-07 13:35 UTC, neSpecc requested changes

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> + * Whenever queue sends ot receives a message, it gets processed using Parsers's methods.
```suggestion
 * Whenever Queue sends or receives a message, it gets processed using Parsers's methods.
```

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> + * For example, if we reiceve a message, we call `parser.parse(msg)`.
```suggestion
 * For example, if we receive a message, we call `parser.parse(msg)`.
```

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> + * Whenever queue sends ot receives a message, it gets processed using Parsers's methods.
и что значит queue sends a message? очередь разве может что-то отправлять куда-то? туда можно положить задачу и можно взять

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> + * You can write your own parser just by inheriting from `Parser` and implementing `prepare` and `parse`.
сразу надо описать, что делают prepare и parse

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> +   * Here you convert a message TO specified data format.
```suggestion
   * Here you convert a message to specified data format.
```

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.js
> +   * Here you convert a message FROM specified data format.
```suggestion
   * Here you convert a message from specified data format.
```

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/parser.test.js
> +describe('JsonParser', () => {
опиши кратко, что проверяет этот тест

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/queue.js
> + * This file is corresponding to queues.
что это значит?

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/queue.js
> +class RedisQueue extends Queue {
лучше вынести в отдельный файл

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/queue.js
> +    this.queueName = queueName;
не задокументированы свойства

2018-11-07 13:35 UTC, neSpecc commented on task-queue/lib/queue.js
> +   * @param {object | Array} msg Message to send.
если известна структура объекта, надо ее указать. И у массива указать тип элементов

2018-11-07 13:38 UTC, kabachook commented on task-queue/lib/parser.js
> + * Whenever queue sends ot receives a message, it gets processed using Parsers's methods.
Имелось в виду класс. Не написал большую букву

2018-11-07 13:39 UTC, kabachook commented on task-queue/lib/queue.js
> +    this.queueName = queueName;
В описании класса написал

2018-11-07 13:40 UTC, kabachook commented on task-queue/lib/queue.js
> +   * @param {object | Array} msg Message to send.
Тут msg - это любой обьект, который можно преобразовать в json строчку

2018-11-08 17:44 UTC, neSpecc approved these changes

2018-11-08 17:44 UTC, neSpecc commented on task-queue/lib/parser.js
> + * `prepare` converts a message to specified format, `parse` converts from specified format to JS object.
```suggestion
 * `prepare` — converts a message to specified format, 
 * `parse` — converts from specified format to JS object.
```

2018-11-08 18:00 UTC, khaydarov approved these changes

2018-11-08 18:04 UTC, merged