Websocket frontend
codex-team/domain-checker pull request #4
Opened 2018-11-08 17:08 UTC by nikmel2803

2018-11-08 17:39 UTC, neSpecc requested changes

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * @param {Function} callback
не описано предназначение параметра

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +      this.socket = new WebSocket(this.apiWS);
написать абстрактную обертку для сокетов по примеру https://github.com/codex-team/hawk.javascript/blob/master/src/modules/websocket.js (но лучше)

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +        if (data !== 'OK' && data !== 'Wrong id') {
расхардкодить строки

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * Main method of the Client class
описание метода должно пояснять, зачем он нужен и что делает

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * @param {String} domainName
не описан параметр

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * @returns {Promise<void>}
она не void возвращает

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +      throw e;
не указано выбрасываемое исключение в доках

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +    alert();
что это

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * Get an id to connect to the server
описать, что речь про id сокета

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * @returns {Promise<String>}
он не строчку возвращает

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +   * @param {String} domainName
не описано назначение параметра

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +      const xhr = new XMLHttpRequest();
вынести Аякс в хелпер или использовать наш готовый https://github.com/codex-team/ajax

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +        resolve(JSON.parse(event.currentTarget.response).id);
parse надо заворачивать в try catch всегда

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/client.js
> +        resolve(JSON.parse(event.currentTarget.response).id);
и надо учесть, что id может не быть в ответе

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  const statusDiv = document.getElementById(ID_STATUS_DIV);
описать константы

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  const API_URI = 'localhost:3000';
API_ENDPOINT

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  const API_WS = `ws://${API_URI}/ws`;
точно ли нужна эта константа?

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  const API_WS = `ws://${API_URI}/ws`;
и API_ID тоже под вопросом

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  const API_WS = `ws://${API_URI}/ws`;
если да, то нужно дать четкие и однозначные названия

2018-11-08 17:39 UTC, neSpecc commented on frontend/src/js/index.js
> +  searchInput.addEventListener('input', Util.debounce(() => {
вынести обработчик в отдельный метод

2018-11-19 14:34 UTC, neSpecc requested changes

2018-11-19 14:34 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +import WebSocketWrapper from './webSocketWrapper';
назови просто Socket

2018-11-19 14:34 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +import WebSocketWrapper from './webSocketWrapper';
и положи в папку `js/utils/`

2018-11-19 14:34 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +      console.log(e);
нужно добавить сообщение к логу

2018-11-19 14:34 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +          if (event.wasClean) {
нужно оставить комментарий к этой части кода

2018-11-19 14:34 UTC, neSpecc commented on frontend/src/js/webSocketWrapper.js
> +
пустые строки между const можно убрать, оставить только после последнего

2018-11-19 15:09 UTC, nikmel2803 commented on frontend/src/js/domainCheckerClient.js
> +import WebSocketWrapper from './webSocketWrapper';
т.е. мне весь файл webSocketWrapper.js скопировать в utils.js? Вместе с документацией и со всем прочим?

2018-11-19 15:10 UTC, nikmel2803 commented on frontend/src/js/domainCheckerClient.js
> +          if (event.wasClean) {
Он сюда вообще нечаянно попал. Можно просто его удалить?

2018-11-19 15:19 UTC, nikmel2803 commented on frontend/src/js/domainCheckerClient.js
> +      console.log(e);
Он сюда вообще нечаянно попал. Можно просто его удалить?

2018-11-19 15:24 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +import WebSocketWrapper from './webSocketWrapper';
нет, создать папку utils и положить туда два файла: socket и debounce

2018-11-19 15:24 UTC, neSpecc commented on frontend/src/js/domainCheckerClient.js
> +      console.log(e);
в любом catch нужно ставить логи

2018-11-19 16:19 UTC, neSpecc approved these changes

2018-11-19 16:29 UTC, khaydarov requested changes

2018-11-19 16:29 UTC, khaydarov commented on frontend/src/js/domainCheckerClient.js
> +   * @throws will throw an error if the AJAX request fail
сюда нужно написать класс который выплевывается. например, checkDomainError или что-то такое

2018-11-19 16:29 UTC, khaydarov commented on frontend/src/js/domainCheckerClient.js
> +    } catch (e) {
а если ты сам здесь же отлавливаешь, то писать не нужно, так как родительский вызов не знает о том, что тут может быть Exception

2018-11-19 16:29 UTC, khaydarov commented on frontend/src/js/domainCheckerClient.js
> +      throw e;
ты этот же класс прокидываешь вверх. в чем смысл? просто в логах? Это лучше сделать тогда в родительском вызове

2018-11-19 16:29 UTC, khaydarov commented on frontend/src/js/utils/debounce.js
> +    inDebounce = setTimeout(() => func.apply(context, args), delay);
ты и так используешь arrow function, func.apply(context, args) ни к чему. можно просто func(args), могу ошибаться, но попробуй

2018-11-19 16:29 UTC, khaydarov commented on frontend/src/js/utils/socket.js
> +    if ('url' in this.options) {
давай просто this.options.url

2018-11-19 16:45 UTC, khaydarov approved these changes

2018-11-19 16:47 UTC, merged