backend
codex-team/domain-checker pull request #8
Opened 2018-11-10 16:35 UTC by nikmel2803

Realizations:
1) WebSocket connection
2) /domain/:domainName method
3) Main page request handler

2018-11-10 17:00 UTC, khaydarov requested changes

2018-11-10 17:00 UTC, khaydarov commented on backend/src/handlers/domain.js
> +  RedisQueue
давай уберем перенос строки, так как там всего лишь один класс импортируется

2018-11-10 17:00 UTC, khaydarov commented on backend/src/handlers/domain.js
> +    redisClient
и тут лишние переносы

2018-11-10 17:00 UTC, khaydarov commented on backend/src/handlers/domain.js
> +      console.error(err);
ты уверен, что после ошибки мы просто выводим в консоль ошибку и продолжаем?

2018-11-10 17:00 UTC, khaydarov commented on backend/src/handlers/ws.js
> +  RedisQueue
Давай все одиночные импорты в одном стиле

2018-11-11 08:13 UTC, khaydarov requested changes

2018-11-11 08:13 UTC, khaydarov commented on backend/src/handlers/domain.js
> +const QUEUE_WHOIS_NAME = 'queue:whois';
После const всегда пуста строка

2018-11-11 08:13 UTC, khaydarov commented on backend/src/handlers/domain.js
> +    const randId = uuid();
И тут

2018-11-11 08:32 UTC, khaydarov approved these changes

2018-11-11 11:22 UTC, neSpecc requested changes

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/domain.js
> +      res.status(400).send('Bad Request');
текст ошибки должен сообщать пользователю, что ему делать

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/domain.js
> +      type: 'whois',
тип надо брать из константы, которые где-то централизованно будут храниться

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout
опиши, зачем используется

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @type {string} Redis valuable which save current tld count
опиши, зачем используется

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @type {string} Redis set key which saves available ids
ids чего?

2018-11-11 11:22 UTC, neSpecc commented on backend/src/handlers/ws.js
> +      if (id.length === 36 && await redisClient.smember(REDIS_ID_SET, id)) {
иф лучше развернуть

2018-11-11 11:22 UTC, neSpecc commented on backend/src/index.js
> +const redisClient = new Redis(REDIS_URL);
в redis надо обязательно включать авторизацию по паролю

2018-11-11 11:25 UTC, kabachook commented on backend/src/index.js
> +const redisClient = new Redis(REDIS_URL);
Пароль можно передать в `REDIS_URL`, `redis://password:user@host:port/db`

2018-11-11 19:06 UTC, neSpecc commented on backend/src/index.js
> +const redisClient = new Redis(REDIS_URL);
их лучше вынести в конфиг или в env

2018-11-11 21:48 UTC, kabachook commented on backend/src/handlers/ws.js
> +      if (id.length === 36 && await redisClient.smember(REDIS_ID_SET, id)) {
Что значит развернуть?

2018-11-11 21:51 UTC, kabachook commented on backend/src/index.js
> +const redisClient = new Redis(REDIS_URL);
Там же уже из env берется `process.env.REDIS_URL` или ты имеешь в виду отдельный файл `.env`?

2018-11-12 13:30 UTC, neSpecc requested changes

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> + * @const {string} Config for Queue and RedisClient
описать, для чего используется

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +const QUEUE_WHOIS_NAME = 'queue:whois';
чем отличается QUEUE_WHOIS_NAME от TASK_TYPE ? и то и другое характеризует тип очереди.

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +    const queueFormer = new RedisQueue({
мы хотели абстрагировать очереди. Чтобы можно было менять движок, не меняя код. То есть тут должен быть вызов `new Queue()` без привязки к конкретному движку. А он внутри должен инициализировать уже Redis или другой движок, в зависимости от конфига

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +  const { redisClient } = req;
откуда тут redisClient?

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +const uuid = require('uuid/v4');
не нравится папка `/handlers/`. Обработчики чего? это воркеры или какая часть структуры?

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +const TASK_TYPE = 'whois';
какие еще будут типы задач? Они должны храниться централизовано, в классе очередей. То есть вызов будет примерно `Queue.task.WHOIS`

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/domain.js
> +const uuid = require('uuid/v4');
вверху файла надо описать его предназначение и что он делает

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +const { RedisQueue } = require('task-queue');
надо написать, что это за файл, зачем он нужен и как работает

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +const QUEUE_RESPONSE_PREFIX = 'queue_response:';
что такое ответ очереди? у очередь не может отвечать. В нее можно добавить элемент и можно достать.

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout for some Redis client commands.
не понятно, для чего нужен

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {string} Redis valuable which contains current number of tlds available to query.
что такое tld? зачем эта переменная нужна?

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +const REDIS_ID_SET = 'ids';
название не соответствует описанию

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +const wsHandler = async (ws, req) => {
надо описать, что делает эта функция

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +      ws.close(1011);
что за magic numbers? нужно брать такие вещи из конфига

2018-11-12 13:30 UTC, neSpecc commented on backend/src/handlers/ws.js
> +      console.error('Can\'t remove id from set');
текст ошибки не понятный и при дебаге ничего не пояснит, даже не понятно будет где это выпало

2018-11-12 13:30 UTC, neSpecc commented on backend/src/index.js
> +const redisClient = new Redis(REDIS_URL);
откуда берется этот REDIS_URL сейчас?

2018-11-12 13:30 UTC, neSpecc commented on backend/src/index.js
> +  app.use(express.static(path.join(__dirname, '../../frontend/src/')));
а это для чего?

2018-11-12 14:00 UTC, kabachook commented on backend/src/handlers/domain.js
> +  const { redisClient } = req;
Из middleware в index.js

2018-11-12 14:05 UTC, kabachook commented on backend/src/handlers/domain.js
> +const uuid = require('uuid/v4');
Это роуты для экспресса, переименую в routes

2018-11-12 14:08 UTC, kabachook commented on backend/src/handlers/ws.js
> +const QUEUE_RESPONSE_PREFIX = 'queue_response:';
Это префикс очереди, содержащей ответ от воркеров

2018-11-12 14:15 UTC, kabachook commented on backend/src/index.js
> +  app.use(express.static(path.join(__dirname, '../../frontend/src/')));
Для удобства разработки, чтобы не подымать nginx для статики, можно хостить эти файлы экспрессом, но тольо в dev environment

2018-11-12 15:30 UTC, kabachook commented on backend/src/handlers/ws.js
> + * @const {string} Redis valuable which contains current number of tlds available to query.
Это количество зон для проверки, сервер будет отдавать клиенту результаты, пока не достигнет этого значения или по таймауту

2018-11-12 15:47 UTC, kabachook commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout for some Redis client commands.
Таймаут для некоторых блокирующих комманд, например, когда вытаскиваем из очереди, то если по таймауту нет элементов чтобы вытащить, он вернет null

2018-11-12 15:57 UTC, neSpecc commented on backend/src/handlers/domain.js
> +const uuid = require('uuid/v4');
ага, так будет лучше

2018-11-12 15:57 UTC, neSpecc commented on backend/src/handlers/ws.js
> +const QUEUE_RESPONSE_PREFIX = 'queue_response:';
но воркеры ничего не отвечают. Они делают свою логику и создают задачи для других воркеров

2018-11-12 15:57 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout for some Redis client commands.
так и надо написать, и привести реальные примеры команд. А что реально 0.003 секунды достаточно? это же почти 0

2018-11-12 15:57 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout for some Redis client commands.
или в каких единицах этот таймаут задается?

2018-11-12 15:57 UTC, neSpecc commented on backend/src/handlers/ws.js
> + * @const {string} Redis valuable which contains current number of tlds available to query.
тогда причем тут REDIS_ ?

2018-11-12 15:57 UTC, neSpecc commented on backend/src/index.js
> +  app.use(express.static(path.join(__dirname, '../../frontend/src/')));
а на продакшене как будет?

2018-11-12 15:59 UTC, kabachook commented on backend/src/handlers/ws.js
> +const QUEUE_RESPONSE_PREFIX = 'queue_response:';
Ответ - доступен ли домен или нет, они кладут его в эту очередь `QUEUE_RESPONSE_PREFIX+task_id`

2018-11-12 16:00 UTC, kabachook commented on backend/src/handlers/ws.js
> + * @const {number} Queue timeout for some Redis client commands.
Таймаут задается в секундах, это исправлю

2018-11-12 16:01 UTC, kabachook commented on backend/src/handlers/ws.js
> + * @const {string} Redis valuable which contains current number of tlds available to query.
Потому что эта переменная хранится в базе, я исправлю чтобы условием закрытия был таймаут или null от очереди

2018-11-12 16:03 UTC, kabachook commented on backend/src/index.js
> +  app.use(express.static(path.join(__dirname, '../../frontend/src/')));
На продакшене `NODE_ENV=production`, соответственно экспресс хостить файлы не будет, этим будет заниматься веб сервер nginx/apache. За счет такого разделения можно горизонтально скейлить бекенд, очереди, и воркеров.

2018-11-13 16:08 UTC, neSpecc commented on backend/src/index.js
> +app.get('/domain/:domain', domainRoute);
описать роуты

2018-11-14 19:00 UTC, neSpecc requested changes

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +# Express port
```suggestion

# Express port
```

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +TASKS_WHOIS=whois
убрать неиспользуемые переменные

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +DOMAIN_REGEXP=[a-zA-Z0-9-]+
это тоже надо убрать

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +WS_CLOSE_OK=1000
```suggestion
WS_STATUS_CLOSED_WITH_OK = 1000
```

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +WS_CLOSE_INVALID_ID = 1008;
```suggestion
WS_STATUS_CLOSED_INVALID_ID = 1008
```

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +const WS_CLOSE_SERVER_ERROR = 1011;
```suggestion
WS_STATUS_CLOSED_SERVER_ERROR = 1011
```

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +const WS_CLOSE_TIMEOUT = 3001;
```suggestion
WS_STATUS_CLOSED_TIMEOUT = 3001
```

2018-11-14 19:00 UTC, neSpecc commented on backend/.env.sample
> +const WS_CLOSE_TIMEOUT = 3001;
но я бы вообще хранил эти коды в модуле ws. 

```js
/**
* Websockets can close connection with one of these codes
*/
const statusCodes = {
  OK: 1000,
  INVALID_ID: 1008,
  SERVER_ERROR: 1011
}
```

и тд

2018-11-14 19:00 UTC, neSpecc commented on backend/src/index.js
> +const domainRoute = require('./routes/domain');
создать папку /api/ и в ней будут храниться роуты api

2018-11-14 19:00 UTC, neSpecc commented on backend/src/index.js
> +const domainRoute = require('./routes/domain');
Пример: https://github.com/codex-team/codex.docs/blob/master/src/routes/index.js

2018-11-14 19:00 UTC, neSpecc commented on backend/src/index.js
>  const hostname = process.env.HOST || '127.0.0.1';
избавиться от этих констант. Брать значение из env

2018-11-14 19:00 UTC, neSpecc commented on backend/src/index.js
> +  req.dbClient = dbClient;
избавиться от этого middleware

2018-11-14 19:00 UTC, neSpecc commented on backend/src/index.js
> +app.get('/api/checkDomain/:domain', domainRoute);
описать роуты

2018-11-14 19:00 UTC, neSpecc commented on backend/src/routes/domain.js
> +const QUEUE_TASKS_NAME = process.env.QUEUE_TASKS_NAME || 'tasks';
избавиться от этих констант. Брать значение из env

2018-11-14 19:00 UTC, neSpecc commented on backend/src/routes/domain.js
> +const domainRoute = async (req, res) => {
описать обработчик

2018-11-14 19:00 UTC, neSpecc commented on backend/src/workers/whois.js
> + * Worker for whois task
описать, что делает воркер с каждой задачей

2018-11-14 19:00 UTC, neSpecc commented on backend/src/workers/whois.js
> +    broker, queueConfig, dbConfig = null
выпилить эти параметры, перенести их в Registry непосредственно

2018-11-14 19:00 UTC, neSpecc commented on backend/src/workers/whois.js
> +   * @param {any} task
описать структуру объекта

2018-11-14 19:00 UTC, neSpecc commented on backend/src/workers/zoneCheck.js
> + * Worker for zoneCheck task
описать, как решаются задачи

2018-11-14 19:00 UTC, neSpecc commented on backend/src/workers/zoneCheck.js
> +   *Creates an instance of ZoneCheckerWorker.
```suggestion
   * Creates an instance of ZoneCheckerWorker.
```

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/registry.js
> +   *Creates an instance of Registry.
```suggestion
   * Creates an instance of Registry.
```

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/registry.js
> +    if (broker === 'redis') {
выбрасывать ошибку при неподдерживаемых брокерах

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/registry.js
> +   * Pop task from registry
from worker's queue

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/registry.js
> +    const queue = QueueFactory.create(this.broker, { ...this.queueConfig, queueName: workerName });
это разве не в конструкторе должно быть?

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/registry.js
> +    const queue = QueueFactory.create(this.broker, { ...this.queueConfig, queueName: workerName });
создаешь очереди, записываешь их в реестр:

```js
{
   [workerName]: Queue(),
   ...
}
```

и обращаешься к реестру

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/worker.js
> +  async start() {
добавить лог `Worker <name> started`

2018-11-14 19:00 UTC, neSpecc commented on worker/lib/worker.js
> +        throw new WorkerError(e);
добавить лог

2018-11-14 19:16 UTC, khaydarov requested changes

2018-11-14 19:16 UTC, khaydarov commented on backend/src/index.js
> + * @const {stirng} Express host
string

2018-11-14 19:16 UTC, khaydarov commented on backend/src/routes/ws.js
> +    if (id.length === 36) {
что за магическое число?

2018-11-15 05:31 UTC, khaydarov requested changes

2018-11-15 05:31 UTC, khaydarov commented on worker/lib/worker.js
> +   * @param {Obejct} queueConfig Queue config passed to new Queue(queueConfig)
Object

2018-11-15 08:57 UTC, neSpecc requested changes

2018-11-15 08:57 UTC, neSpecc commented on backend/src/api/domain.js
> +    const randId = uuid();
answersSocketId

2018-11-15 08:57 UTC, neSpecc commented on backend/src/api/domain.js
> +    res.status(200).send(randId);
ответы api должны быть в формате JSON:

```jsonp
{
  "success": 1,
  "data": {
    "channelId": answersSocketId
  }
}
```

2018-11-15 08:57 UTC, neSpecc commented on backend/src/api/ws.js
> + * @const {number} Task id length
не описано, для чего используется эта константа

2018-11-15 08:57 UTC, neSpecc commented on backend/src/api/ws.js
> + * @const {number} Task id length
и судя по коду, это не task id, а channel Id

2018-11-15 13:22 UTC, neSpecc approved these changes

2018-11-15 15:16 UTC, khaydarov approved these changes

2018-11-15 15:20 UTC, merged